import { CareerProps } from "../types/careers";

export const CAREERS: CareerProps[] = [
  {
    position: "Backend Golang Developer",
    company: "Pt. Affan Technology Indonesia (Parto.id)",
    logo: "/images/careers/parto-id.png",
    location: "Jambi, Indonesia 🇮🇩",
    location_type: "Hybrid",
    type: "Internship",
    start_date: "2025-07",
    end_date: "2025-09",
    industry: "Marketplace B2B/B2G",
    link: "https://parto.id/",
    responsibilities: [
      "Developed and maintained backend services using Golang for Parto.id's internal attendance application.",
      "Implemented efficient data handling and secure API integrations to support daily attendance workflows.",
      "Collaborated with frontend and product teams to ensure smooth functionality and seamless user experience.",
    ],
    lessons_learned: [
      "Deepened understanding of Go's concurrency model and Clean Architecture within a production environment.",
      "Gained hands-on experience in implementing Agile Scrum methodologies to streamline development workflows.",
      "Learned to collaborate effectively within a professional development team to achieve collective project goals.",
    ],
    impact: [
      "Developed core APIs for essential functionalities, including clock-in/clock-out systems, leave management (listing and requesting), and employee profile management (GET/UPDATE).",
      "Improved system reliability for internal tools by optimizing database queries for employee records and leave history.",
    ],
    isShow: true,
  },
  {
    position: "Frontend Web Developer",
    company: "Pt. Eltran Indonesia",
    logo: "/images/careers/eltran-indonesia.png",
    location: "Bandung, Indonesia 🇮🇩",
    location_type: "Remote",
    type: "Internship",
    start_date: "2025-05",
    end_date: "2025-11",
    industry: "Engineering, Procurement & Construction (EPC)",
    link: "https://eltran.co.id/",
    responsibilities: [
      "Developed a responsive and interactive landing page using Next.js to promote company services and solutions.",
      "Ensured SEO optimization and fast performance by leveraging Next.js features such as static site generation.",
      "Collaborated with design and marketing teams to align web presence with brand identity.",
    ],
    lessons_learned: [
      "Mastered Next.js performance optimization (Core Web Vitals) and SEO best practices.",
      "Learned to bridge the gap between technical implementation and corporate branding requirements.",
    ],
    impact: [
      "Enhanced the company's digital visibility, leading to a significant increase in organic web traffic.",
      "Improved website loading speed, achieving a high Performance Score on Lighthouse.",
    ],
    isShow: false,
  },
  {
    position: "Head of Technology in the Research and Technology Division",
    company:
      "Himpunan Mahasiswa Sistem Informasi Universitas Jambi (HIMASI UNJA)",
    logo: "/images/careers/himasi-unja.jpeg",
    location: "Jambi, Indonesia 🇮🇩",
    location_type: "Onsite",
    type: "Part-time",
    start_date: "2024-12",
    end_date: "2025-12",
    industry: "School/Organization",
    link: "https://himasi.unja.ac.id/",
    responsibilities: [
      "Led the development of an internal RFID-based attendance system for HIMASI UNJA.",
      "Managed the technical team and oversaw the implementation of hardware-software integration.",
      "Ensured the system was user-friendly, secure, and met the organization's operational needs.",
    ],
    lessons_learned: [
      "Developed leadership skills and project management capabilities in a team setting.",
      "Gained hands-on experience in IoT integration and connecting hardware with web-based databases.",
    ],
    impact: [
      "Digitalized the organization's attendance process, eliminating paper waste and improving data accuracy.",
      "Successfully led a team of 5+ students to deliver the project on schedule.",
    ],
    isShow: true,
  },
  {
    position: "Mobile Development Cohort",
    company: "Bangkit Academy led by Google, Tokopedia, Gojek & Traveloka",
    logo: "/images/careers/bangkit.png",
    location: "Remote",
    location_type: "Remote",
    type: "Part-time",
    start_date: "2024-09",
    end_date: "2024-12",
    industry: "Education/Technology",
    link: "https://grow.google/intl/id_id/bangkit/",
    responsibilities: [
      "Mastered Android development using Kotlin, Jetpack Components, and modern tools like Room and DataStore.",
      "Gained hands-on experience with ViewModel, RecyclerView, and Hilt for dependency injection.",
      "Collaborated with a cross-functional team to develop a Company-Based Capstone Project.",
    ],
    lessons_learned: [
      "Deepened technical expertise in native Android development and MVVM architecture.",
      "Learned professional collaboration using Agile methodologies and Git-flow.",
    ],
    impact: [
      "Selected as part of the 'Best Team' for the Company Track Capstone Project among hundreds of participants.",
      "Successfully built and deployed a production-ready mobile application as a solution for partner companies.",
    ],
    isShow: true,
  },
  {
    position: "Mobile Developer",
    company: "Pt. Amanah Karya Indonesia (Amanah Corp)",
    logo: "/images/careers/amanah-karya-indonesia.jpeg",
    location: "Depok, Indonesia 🇮🇩",
    location_type: "Remote",
    type: "Part-time",
    start_date: "2024-10",
    end_date: "2024-12",
    industry: "Technology/Philanthropy",
    link: "https://amanahcorp.co.id/",
    responsibilities: [
      "Designed and developed a mobile application using Kotlin, incorporating Room Database, Hilt, and ViewModel.",
      "Implemented secure and user-friendly features tailored to the berbagi.link platform.",
      "Worked closely with PT Amanah Corp to ensure alignment with business objectives.",
    ],
    lessons_learned: [
      "Understood the lifecycle of product development from ideation to deployment in a corporate setting.",
      "Improved ability to translate business requirements into technical features.",
    ],
    impact: [
      "Contributed to the development of the 'berbagi.link' mobile ecosystem, enhancing accessibility for users.",
      "Streamlined app performance by implementing efficient state management and local caching.",
    ],
    isShow: true,
  },
];
